Repository ssg-240304-java2/shop-techmya, pull requests merged in 2024-06, with the labels that each got.

#60 초기설정 세팅 및 폴더 추가
  project/techmya/src/main/resources/static/admin/admin-main.html
  project/techmya/src/main/resources/static/index.html
  project/techmya/src/main/resources/static/shop/index.html
Labels: good first issue

#75 #2 회원가입 및 로그인 구현
  .idea/.gitignore
  .idea/misc.xml
  .idea/vcs.xml
  project/techmya/gradle/wrapper/gradle-wrapper.properties
  project/techmya/src/main/java/com/ohgiraffers/techmya/configuration/MybatisConfiguration.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/member/controller/UserController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/member/model/dao/UserMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/member/model/dto/UserDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/member/model/service/UserService.java
  project/techmya/src/main/resources/application.yml
  project/techmya/src/main/resources/mappers/UserMapper.xml
  project/techmya/src/main/resources/mappers/stock/StockMapper.xml
  project/techmya/src/main/resources/static/index.html
  project/techmya/src/main/resources/templates/admin-main.html
  project/techmya/src/main/resources/templates/admin/main.html
  project/techmya/src/main/resources/templates/board/board.html
  project/techmya/src/main/resources/templates/common/admin/fragments/header.html
  project/techmya/src/main/resources/templates/login/main.html
  project/techmya/src/main/resources/templates/member/login.html
  project/techmya/src/main/resources/templates/member/signup.html
Labels: 🔧Feat.

#76 #61 [2024-06-26] 추가 fragment layout 및 table 업데이트
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/order/model/dto/OrderCancleDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/order/model/dto/OrderDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/order/model/dto/OrderDetailDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/ShopProductController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/order/model/service/OrderService.java
  project/techmya/src/main/resources/static/index.html
  project/techmya/src/main/resources/templates/admin/order/orderList.html
  project/techmya/src/main/resources/templates/common/admin/fragments/navOrder.html
  project/techmya/src/main/resources/templates/shop/orderTest.html
  project/techmya/src/main/resources/templates/shop/products.html
Labels: Common

#77 #62 PR
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/controller/StockController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/controller/AdminController.java
  project/techmya/src/main/resources/templates/admin-main.html
  project/techmya/src/main/resources/templates/admin/main.html
  project/techmya/src/main/resources/templates/admin/stock/stockmain.html
  project/techmya/src/main/resources/templates/admin/stock/stockmanage.html
  project/techmya/src/main/resources/templates/common/admin/fragments/header.html
  project/techmya/src/main/resources/templates/common/admin/layouts/navlayout.html
Labels: 🔧Feat.

#78 계시판 html연결 완료
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/controller/PostController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/dto/PostDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/member/controller/UserController.java
  project/techmya/src/main/resources/templates/admin-main.html
  project/techmya/src/main/resources/templates/admin/board/boardMain.html
  project/techmya/src/main/resources/templates/admin/board/edit.html
  project/techmya/src/main/resources/templates/admin/board/reply.html
  project/techmya/src/main/resources/templates/admin/board/write.html
  project/techmya/src/main/resources/templates/board/board.html
Labels: 🔧Feat.

#80 #41 [2024-06-27] 주문관리 구매자/장바구니 담기 완료
  .gitignore
  project/techmya/.gitignore
  project/techmya/build.gradle
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/order/model/dto/OrderDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/order/model/dto/OrderDetailDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/ShopProductController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/order/controller/ShopProductController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/order/model/dao/OrderMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/order/model/dto/OrderCartDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/order/model/service/OrderService.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/order/model/service/OrderServiceImpl.java
  project/techmya/src/main/resources/application.yml
  project/techmya/src/main/resources/mappers/shopOrder/OrderMapper.xml
  project/techmya/src/main/resources/templates/common/shop/fragments/header.html
  project/techmya/src/main/resources/templates/shop/orderCart.html
  project/techmya/src/main/resources/templates/shop/orderProduct.html
  project/techmya/src/main/resources/templates/shop/orderTest.html
Labels: 🔧Feat.

#81 #71 [주문관리 통합/ 프론트엔드] 대시보드 메뉴 동작 안하는 문제 수정
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/order/OrderController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/order/controller/ShopProductController.java
  project/techmya/src/main/resources/templates/admin-main.html
  project/techmya/src/main/resources/templates/admin/order/ordermain.html
  project/techmya/src/main/resources/templates/common/admin/fragments/header.html
  project/techmya/src/main/resources/templates/common/admin/fragments/navOrder.html
  project/techmya/src/main/resources/templates/common/admin/layouts/navlayout.html
Labels: Common

#84 #48 [2024-06-27] Feat.Stock SelectAll
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/controller/StockController.java
  project/techmya/src/main/resources/mappers/stock/StockMapper.xml
  project/techmya/src/main/resources/templates/admin/stock/stockmain.html
  project/techmya/src/main/resources/templates/admin/stock/stockmanage.html
  project/techmya/src/main/resources/templates/common/admin/fragments/header.html
  project/techmya/src/main/resources/templates/common/admin/layouts/navlayout.html
Labels: 🔧Feat.

#87 #47 [ 2024-06-27 ] ing
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/controller/StockController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/dao/StockMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/dto/inputStockDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/dto/outputStockDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/service/StockService.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/service/StockServiceImp.java
  project/techmya/src/main/resources/application.yml
  project/techmya/src/main/resources/mappers/stock/StockMapper.xml
  project/techmya/src/main/resources/templates/admin/stock/inmanage.html
  project/techmya/src/main/resources/templates/admin/stock/stockmain.html
Labels: 🔧Feat.

#88 Board 기능하는중
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/controller/ImageController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/controller/PostController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/dao/PostMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/dto/PostDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/dto/PostImageDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/dto/ReplyDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/service/PostService.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/service/PostServiceImpl.java
  project/techmya/src/main/resources/application.yml
  project/techmya/src/main/resources/mappers/PostMapper.xml
  project/techmya/src/main/resources/templates/admin/board/boardMain.html
  project/techmya/src/main/resources/templates/admin/board/edit.html
  project/techmya/src/main/resources/templates/admin/board/reply.html
  project/techmya/src/main/resources/templates/admin/board/view.html
  project/techmya/src/main/resources/templates/admin/board/write.html
  project/techmya/uploads/184794_184983_4131.jpg
  project/techmya/uploads/images.jpg
  project/techmya/uploads/캡처.PNG
  project/techmya/uploads/회원가입 페이지.PNG
Labels: 🔧Feat.

#89 #30 Feat:상품 등록 [추가 정보]
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/product/controller/ProductController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/product/model/dao/PostMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/product/model/dto/ProductAndProductPostDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/product/model/service/ProductPostService.java
  project/techmya/src/main/resources/mappers/product/PostMapper.xml
  project/techmya/src/main/resources/templates/admin/product/post.html
  project/techmya/src/main/resources/templates/admin/product/postregist.html
  project/techmya/src/main/resources/templates/admin/product/productmain.html
  project/techmya/src/main/resources/templates/admin/product/regist.html
Labels: 🔧Feat.

#90 #52 [2024-06-27] Feat. InWarehousing SelectAll
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/controller/InStockController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/controller/StockController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/dao/StockMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/dto/InWHDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/service/StockService.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/service/StockServiceImp.java
  project/techmya/src/main/resources/mappers/stock/StockMapper.xml
  project/techmya/src/main/resources/templates/admin-main.html
  project/techmya/src/main/resources/templates/admin/stock/inmanage.html
  project/techmya/src/main/resources/templates/admin/stock/outmanage.html
  project/techmya/src/main/resources/templates/admin/stock/stockmain.html
  project/techmya/src/main/resources/templates/admin/stock/stockmanage.html
Labels: 🔧Feat.

#91 Bug: 상품 추가정보 등록 기능까지 버그 확인
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/product/model/dao/ProductPostMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/product/model/service/ProductPostService.java
  project/techmya/src/main/resources/mappers/product/ProductPostMapper.xml
Labels: bug

#92 #56 [2024-06-27] Feat.OutWarehousing Select All
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/controller/OutStockController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/dao/StockMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/dto/OutStockDTO.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/service/StockService.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/model/service/StockServiceImp.java
  project/techmya/src/main/resources/mappers/stock/StockMapper.xml
  project/techmya/src/main/resources/templates/admin/stock/inmanage.html
  project/techmya/src/main/resources/templates/admin/stock/outmanage.html
  project/techmya/src/main/resources/templates/admin/stock/stockmain.html
Labels: 🔧Feat.

#94 [주문관리 통합/프론트엔드] 중간 pr입니다.
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/order/controller/OrderListController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/controller/LoginController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/order/controller/ShopProductController.java
  project/techmya/src/main/resources/static/index.html
  project/techmya/src/main/resources/templates/admin-main.html
  project/techmya/src/main/resources/templates/admin/order/ordermain.html
  project/techmya/src/main/resources/templates/common/admin/fragments/header.html
  project/techmya/src/main/resources/templates/common/admin/fragments/navOrder.html
  project/techmya/src/main/resources/templates/common/admin/layouts/navlayout.html
  project/techmya/src/main/resources/templates/shop/orderCart.html
  project/techmya/src/main/resources/templates/shop/productdetail.html
  project/techmya/src/main/resources/templates/shop/products.html
Labels: 🔧Feat.

#95 #93 for README.md ing....
  README.md
Labels: Common

#98 프론트 통합: stock완료
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/product/controller/ProductController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/controller/InStockController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/controller/OutStockController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/stock/controller/StockController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/controller/PostController.java
  project/techmya/src/main/resources/templates/admin-main.html
  project/techmya/src/main/resources/templates/admin/product/post.html
  project/techmya/src/main/resources/templates/admin/stock/inmanage.html
  project/techmya/src/main/resources/templates/admin/stock/outmanage.html
  project/techmya/src/main/resources/templates/admin/stock/stockmain.html
  project/techmya/src/main/resources/templates/common/admin/layouts/navlayout.html
Labels: 🔧Feat.

#100 계시판
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/controller/PostController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/dao/PostMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/service/PostService.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/board/model/service/PostServiceImpl.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/controller/AdminController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/controller/LoginController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/member/controller/AdminController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/member/controller/UserController.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/member/model/dao/UserMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/member/model/service/UserService.java
  project/techmya/src/main/resources/mappers/UserMapper.xml
  project/techmya/src/main/resources/static/index.html
  project/techmya/src/main/resources/templates/admin-main.html
  project/techmya/src/main/resources/templates/admin/board/boardMain.html
  project/techmya/src/main/resources/templates/admin/board/edit.html
  project/techmya/src/main/resources/templates/admin/board/view.html
  project/techmya/src/main/resources/templates/board/board.html
  project/techmya/uploads/1324878-wrigley-field-hd-wallpaper-1920x1080-htc.jpg
  project/techmya/uploads/83d8d0aaaf580f60782adb8a2cc509d9.jpg
  project/techmya/uploads/B069F215-7344-49C1-8548-70425427DC39-22206-0000104FDB5CA962_file.jpg
  project/techmya/uploads/XUMyWMVTQuWZGbXhYOOHl8iIyuTKPWVIQVrng64icrZtBzHBlgr5KoXAf4ZjRwAZSXo8NWUXgCd6i6jlGmEe8cWu_3IZKzTnIA6c2romaujUBBw4qHZ4PBDZ0fOvmYsdeNk8raOPlvl07ILfdCYosA.webp
  project/techmya/uploads/images.jpg
  project/techmya/uploads/다운로드 (2).jpg
Labels: bug

#102 Fix 5tas
  project/techmya/src/main/resources/templates/admin/stock/inmanage.html
  project/techmya/src/main/resources/templates/common/admin/layouts/navlayout.html
Labels: bug

#104 샵페이지에서 board보이게 변경했습니다
  project/techmya/src/main/resources/static/index.html
Labels: bug

#107 Feat/product
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/product/model/dao/ProductDisplayMapper.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/admin/product/model/service/ProductDisplayService.java
  project/techmya/src/main/java/com/ohgiraffers/techmya/shop/order/controller/ShopProductController.java
  project/techmya/src/main/resources/mappers/product/ProductDisplayMapper.xml
  project/techmya/src/main/resources/templates/admin/product/postregist.html
  project/techmya/src/main/resources/templates/admin/product/regist.html
  project/techmya/src/main/resources/templates/shop/products.html
Labels: 🔧Feat.

#108 it's readme
  README.md
  project/techmya/src/main/resources/templates/common/admin/layouts/navlayout.html
Labels: documentation
